const Gift = require('../models/gift');
const data = {
  "slug": "momo",
  "recipient": "Momo",
  "greeting": "Feliz cumpleaños, mi amor",
  "photos": [
    {"src":"/photos/foto-1.jpg","title":"Un momento que guardo para siempre","text":"Un pedacito de nuestra historia."},
    {"src":"/photos/foto-2.jpg","title":"Tú y yo","text":"Porque contigo hasta lo sencillo se siente especial."},
    {"src":"/photos/foto-3.jpg","title":"De esos días bonitos","text":"Un recuerdo que todavía me hace sonreír."},
    {"src":"/photos/foto-4.jpg","title":"Una sonrisa que amo","text":"De esas pequeñas cosas que nunca olvido."},
    {"src":"/photos/foto-5.jpg","title":"Nuestra historia","text":"Otro recuerdo para volver a visitar."},
    {"src":"/photos/foto-16.jpg","title":"Otro pedacito de nosotros","text":"Un instante que merece quedarse aquí."},
    {"src":"/photos/IMG_20250106_133249.jpg","title":"Un recuerdo especial","text":"De esos momentos que vuelven con solo mirar una foto."},
    {"src":"/photos/WhatsApp Image 2026-08-23 at 7.13.27 PM.jpeg","title":"Una tarde para recordar","text":"Pequeños momentos, grandes recuerdos."},
    {"src":"/photos/WhatsApp Image 2026-08-23 at 7.13.27 PM (1).jpeg","title":"Siempre tú","text":"Una imagen más para guardar cerquita del corazón."},
    {"src":"/photos/WhatsApp Image 2026-08-23 at 7.13.27 PM (2).jpeg","title":"Juntos en un instante","text":"Porque cada recuerdo tiene su propia historia."},
    {"src":"/photos/WhatsApp Image 2026-08-23 at 7.13.28 PM.jpeg","title":"Un día bonito","text":"De esos que dan ganas de volver a vivir."},
    {"src":"/photos/WhatsApp Image 2026-08-23 at 7.16.33 PM.jpeg","title":"Una sonrisa más","text":"Otro momento que se queda para siempre."},
    {"src":"/photos/WhatsApp Image 2026-08-23 at 7.16.33 PM (1).jpeg","title":"Momentos que cuentan","text":"Una parte más de nuestra historia."},
    {"src":"/photos/WhatsApp Image 2026-08-23 at 7.16.33 PM (2).jpeg","title":"Y los que faltan…","text":"Porque este álbum puede seguir creciendo."}
  ],
  "letter": {
    "greeting": "Para mi Momo, en tu cumpleaños ❤️",
    "paragraphs": [
      "Mi Momo. Mi Momis.",
      "Hoy es 25 de agosto y, por primera vez, siento que tengo el valor de escribirte la carta que debí darte hace mucho tiempo.",
      "¿Te acuerdas cuando fui a visitarte de sorpresa por uno de tus cumpleaños? Todas tus amigas y tu familia tenían una carta para ti. Yo no la hice. En ese momento no entendí la importancia de poner en palabras lo que sentía, y hoy me arrepiento profundamente de eso. Fui un bobo… como tantas veces en mi vida.",
      "Así que este año quiero regalarte algo que nace desde el lugar más sincero de mi corazón.",
      "Feliz cumpleaños, mi amor.",
      "Antes que cualquier otra cosa, deseo que la vida te abrace bonito. Que sigas siendo esa mujer llena de luz, con esa chispa de emprendedora que siempre admiré. Que nunca te falten girasoles, mariposas, música en vivo y razones para sonreír.",
      "Porque, aunque hoy no estemos juntos, nunca voy a dejar de querer que seas inmensamente feliz.",
      "Han pasado casi cinco meses desde la última vez que hablamos. Te bloqueé de las redes y quizá algún día pienses que fue por orgullo, pero la verdad es mucho más simple: lo hice porque no era capaz de verte. Cada foto, cada estado y cada recuerdo me rompían un poquito el corazón. Pensé que alejándome iba a dejar de extrañarte… y me equivoqué.",
      "Aunque hubo algo que rompió ese silencio hace poco.",
      "El día del temblor vi una llamada perdida tuya. Después de tantos meses sin hablar, ver tu nombre en mi teléfono me produjo una felicidad que no sé cómo explicar. Por un momento solo pensé: “Momo me está llamando.”",
      "Y aunque no quiero darle a esa llamada un significado que quizás no tenga, sí me recordó algo que para mí es importante: en ese momento pensaste en mí y quisiste saber si estaba bien y escucharte otra vez fue un recordatorio de que, pase lo que pase entre nosotros, lo que vivimos fue real y siempre significará muchísimo para ambos...",
      "Quizás para ti fue simplemente una llamada, pero para mí fue un pequeño instante de felicidad después de muchos meses de extrañarte.",
      "Todavía basta con escuchar una salsa romántica para que aparezcas en mi cabeza. Y también basta con escuchar música electrónica para sonreír, porque inmediatamente recuerdo nuestras noches en el Freedom.",
      "¿Sabes qué era lo que más me enamoraba de esas noches?",
      "Que tú realmente no ibas porque amaras esa música. Ibas porque me amabas a mí.",
      "Me acompañabas a bailamos; conociste a mis amigos y terminaste siendo parte del grupo como si siempre hubieras pertenecido.",
      "Nunca había compartido esa parte de mi vida con una mujer, y contigo todo era natural. Hoy entiendo que ese era uno de los actos de amor más bonitos que hiciste por mí: entrar en mi mundo solo para verme feliz.",
      "Y eso me enamoraba.",
      "Porque no necesitabas amar la electrónica.",
      "Te bastaba con quererme.",
      "Y por eso ibas.",
      "Y luego están esos recuerdos que viven conmigo como si hubieran pasado ayer.",
      "La Unión. Tú con ese pantalón blanco y negro y la chaqueta de cuero. Nosotros cantando en ese barcito, riéndonos de cualquier bobada y creyendo, sin decirlo, que el tiempo podía detenerse.",
      "San Francisco. Yo trabajando en la mina y tú pasabas la semana conmigo. Llegar cansado y abrir la puerta para encontrarte esperándome era una de las sensaciones más felices de mi vida.",
      "Recuerdo verte allí y pensar que esa mujer tan hermosa estaba conmigo, por mí.",
      "Y yo era feliz.",
      "Muy feliz.",
      "Nunca te lo dije suficiente.",
      "Y después está cuando tu regresaste de Italia…",
      "Creo que ahí empezó el amor más grande que he sentido.",
      "Tú estabas donde tu tía y yo no tenía idea de lo que estabas preparando. Le dijiste a mi tía que me llevara a un restaurante y que me sentara de espaldas a la entrada.",
      "Yo estaba allí, pensando que era una comida cualquiera.",
      "Hasta que Volteé…",
      "Y ahí estabas tú.",
      "Con un vestido negro.",
      "Meliche había regresado desde tan lejos para sorprenderme y para ser mi momo.",
      "Y creo que ese fue uno de los momentos en los que realmente entendí cuánto valías para mí.",
      "Desde ese día empezó a crecer dentro de mí un amor que nunca había sentido por nadie.",
      "Momis, yo amo absolutamente todo de ti.",
      "Tu piel morena y suave.",
      "Tu aroma, ese olor que para mí siempre fue como a pastelito.",
      "Tu cabello mono, aunque los dos sepamos que era tinturado.",
      "Tus piernas.",
      "Tu sentido del humor, tan parecido al mío.",
      "Tu forma de tratarme.",
      "Tu manera de querer.",
      "Tu forma de hacerme sentir amado.",
      "Tu sonrisa.",
      "Tus ocurrencias.",
      "Tu gusto exagerado por los buñuelos.",
      "La Corpo el bar que tanto te gustaba por la música en vivo.",
      "Tus girasoles.",
      "Tus mariposas.",
      "Y hasta esas pequeñas cosas que dejaste en mi cuarto.",
      "Ayer estuve organizándolo y me encontré con tus shorts, un cholo que se quedó aquí, una de las conchas de mar que me trajiste de Italia la más pequeñita que la guardé a parte porque te gustaba por chiquita y los dos llaveros: el cactus y la patineta que dice Italia.",
      "Me quedé mirándolos y pensé:",
      "¿Cómo puede alguien no estar y seguir estando en todos los rincones de mi vida?",
      "Porque eso eres tú.",
      "No estás aquí, pero sigues viviendo en las canciones, en mi cuarto, en mis recuerdos y en mi corazón.",
      "Durante mucho tiempo yo arreglaba mi cuarto pensando en ti. Lo limpiaba, organizaba las cosas y para que cuando vinieras te sintieras cómoda, como si ese lugar también fuera un poquito tuyo.",
      "Y quizás por eso me cuesta tanto ver ahora todas esas cosas.",
      "Porque cada una me recuerda a una época en la que esperaba que llegaras.",
      "Y todavía hay una parte de mí que quisiera volver a preparar ese cuarto para ti.",
      "También necesito pedirte perdón.",
      "No un perdón para borrar lo que hice, porque sé que eso no existe.",
      "Te engañé.",
      "Te fallé cuando esperabas apoyo.",
      "Hubo momentos en los que necesitabas un compañero y no supe serlo.",
      "Tú siempre tuviste esa fuerza para emprender, para soñar en grande, y quizá yo no entendí cómo impulsarte. La distancia tampoco ayudó: tú en Ciudad Bolívar y yo en Marinilla, viéndonos apenas una vez al mes.",
      "Hablábamos todos los días, si, pero hoy entiendo que hablar no siempre significa estar verdaderamente presente.",
      "Y yo debí estar mucho más presente.",
      "Debí escucharte mejor.",
      "Debí apoyarte más.",
      "Debí cuidarte más.",
      "Debí valorar mucho más a la mujer que tenía.",
      "Y lo siento.",
      "Sé que decirlo ahora no cambia lo que pasó, pero necesitaba que lo supieras.",
      "Hay algo que me duele especialmente recordar.",
      "Cuando en esa terraza tomando cocteles tú me dijiste.",
      "Que querías hijos.",
      "que soñabas con una familia…",
      "Y fui yo quien dijo que no quería más hijos ni casarme.",
      "Si pudiera volver a ese momento, abrazaría a ese Sebastián y le diría:",
      "“No seas idiota. Estás frente a la mujer con la que vas a querer pasar el resto de tu vida.”",
      "Porque hoy mi respuesta sería completamente distinta.",
      "Sí quisiera vivir contigo.",
      "Sí quisiera construir una familia contigo.",
      "Sí quisiera casarme contigo.",
      "Me haría feliz despertar algún día y encontrarte a mi lado.",
      "Me haría feliz construir una casa contigo, llegar del trabajo y encontrarte allí, salir a comer unos buñuelos, ir a escuchar música, viajar, ir a una fiesta, ir a un concierto o simplemente quedarnos juntos sin hacer absolutamente nada.",
      "No porque hoy esté solo.",
      "Sino porque después de perderte entendí que eras tú con quien quería compartir la vida.",
      "También sé que tú hiciste sacrificios por mí.",
      "Y uno de los que más recuerdo es aquel día en que regresaste de Italia.",
      "Hoy entiendo mucho más lo que significó ese gesto.",
      "Tú pudiste quedarte allá.",
      "Pero regresaste.",
      "Y yo espero que algún día hayas sabido cuánto significó eso para mí.",
      "Momo, no te escribo esta carta para pedirte que olvides mis errores.",
      "Y aunque sería mentira decir que no sueño con volver contigo, quiero que sepas que jamás quisiera que regresaras por lástima.",
      "Si algún día nuestros caminos vuelven a unirse, quiero que sea porque los dos lo elegimos.",
      "Porque tú también lo sientes.",
      "Porque los dos creemos que vale la pena intentarlo otra vez.",
      "Solo necesito que sepas una cosa:",
      "Yo te amo.",
      "Te amo como a nada en este mundo.",
      "Y tienes mi corazón hasta que tú decidas devolvérmelo.",
      "Voy a seguir con mi vida.",
      "Voy a trabajar.",
      "Voy a crecer.",
      "Voy a aprender.",
      "Voy a intentar convertirme en un mejor hombre.",
      "No quiero quedarme detenido esperando que regreses y olvidarme de vivir.",
      "Quiero seguir adelante.",
      "Pero eso no significa que tenga que dejar de amarte.",
      "Y si algún día la vida te trae nuevamente hacia mí, me vas a encontrar.",
      "No siendo el mismo Sebastián.",
      "Sino uno que haya aprendido de sus errores.",
      "Uno que sepa valorar.",
      "Uno que sepa estar.",
      "Uno que quiera apoyarte en tus sueños.",
      "Uno que quiera celebrar tus logros.",
      "Uno que quiera acompañarte.",
      "Uno que quiera cuidarte.",
      "Uno que quiera construir contigo.",
      "Uno que, si algún día vuelves a querer una familia, esté listo para construirla contigo.",
      "Gracias, Momo.",
      "Gracias por haberme enseñado qué era amar.",
      "Gracias por haber ido conmigo al Freedom.",
      "Gracias por haber conocido a mis amigos y convertirte en parte de mi mundo.",
      "Gracias por cantar conmigo en  la ducha.",
      "Gracias por esperarme en San Francisco.",
      "Gracias por volver desde Italia y regalarme una de las sorpresas más hermosas de mi vida.",
      "Gracias por tus girasoles.",
      "Por tus mariposas.",
      "Por tus canciones.",
      "Por tus buñuelos.",
      "Por tus abrazos.",
      "Por tu manera de quererme.",
      "Por esas cogidas a lo mal hecho jaajajajajja.",
      "Gracias por esos cuatro años.",
      "Gracias por haberme hecho feliz.",
      "Y gracias incluso por haberme dejado.",
      "Porque perderte me obligó a entender cosas que cuando te tenía no fui capaz de ver.",
      "Hoy no quiero celebrar que algún día fuiste mi novia.",
      "Quiero celebrar que naciste.",
      "Que existes.",
      "Que tuve el privilegio de coincidir contigo en esta vida.",
      "Ojalá cumplas todos tus sueños.",
      "Ojalá emprendas todo eso que alguna vez soñaste.",
      "Ojalá viajes.",
      "Ojalá conozcas el mundo.",
      "Ojalá escuches mucha salsa.",
      "Ojalá bailes.",
      "Ojalá te rías muchísimo.",
      "Ojalá tengas muchos girasoles y mariposas.",
      "Y ojalá nunca pierdas esa chispa que te hace ser tú.",
      "Y si algún día, mientras escuchas una salsa, ves una mariposa, encuentras un girasol, escuchas una canción electrónica o simplemente pasas por algún lugar que te recuerde a nosotros, te acuerdes de mí…",
      "Espero que sonrías.",
      "No quiero que me recuerdes solamente por mis errores.",
      "Quiero que recuerdes también todo lo bonito que vivimos.",
      "Porque hubo un hombre que quizá fue muy bobo.",
      "Que cometió errores enormes.",
      "Que muchas veces la cagó.",
      "Pero que te amó con toda el alma.",
      "Momo…",
      "Yo no sé cuándo dejaré de amarte.",
      "Y sinceramente, ya no estoy intentandolo.",
      "Porque quizás algunas personas no se dejan de amar.",
      "Simplemente aprendemos a llevarlas dentro de nosotros de una manera diferente.",
      "Tú tienes un pedazo de mi corazón.",
      "Y lo vas a tener hasta el día en que tú misma decidas devolvérmelo.",
      "No sé qué va a pasar mañana.",
      "No sé dónde nos va a poner la vida.",
      "No sé si algún día volveremos a ser nosotros.",
      "Pero sí sé que, si algún día decides regresar, quiero recibirte siendo una mejor versión de mí.",
      "Y si nunca sucede…",
      "igual voy a estar agradecido.",
      "Porque durante cuatro años tuve la oportunidad de amar a la mujer que, hasta hoy, ha sido la mujer que más feliz me ha hecho.",
      "Te amo, Momo.",
      "Te amo por lo que fuiste.",
      "Te amo por lo que eres.",
      "Y quizás, en algún lugar de mi corazón, también te amo por lo que algún día podríamos volver a ser.",
      "Feliz cumpleaños, mi Momis.",
      "Que la vida te regale todo lo bonito que mereces.",
      "Y que nunca olvides que, en algún lugar de Marinilla, hay un cuarto donde todavía quedan pequeñas cosas tuyas y que siempre estarán ahí junto a un corazón que todavía lleva tu nombre.",
      "Con todo mi amor,",
      "Sebastián ❤️"
    ],
    "signature": "Con todo mi amor,\nSebastián ❤️"
  },
  "closing": {
    "eyebrow": "DISFRUTA TU DIA",
    "title": "Por muchos recuerdos más auque no sean a mi lado.",
    "text": "Feliz cumpleaños, mi Momis. ✨"
  }
};

const seedGift = async () => {
  await Gift.findOneAndUpdate({ slug: data.slug }, data, { upsert: true, new: true, setDefaultsOnInsert: true });
  console.log('Regalo de Momo cargado en MongoDB');
};
module.exports = seedGift;
